const keigenns = {
  "4a7": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 铁壁
  "740": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 盾阵
  "496": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 干预
  "4a": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 预警
  "498": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 武装
  "52": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 神圣领域
  "552": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 6.3新圣光幕帘
  "a72": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 圣盾阵
  "a73": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 骑士的坚守
  "4d": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 6.4壁垒
  "2df": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 原初的直觉
  "8b3": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 原初的勇猛
  "57": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 战栗
  "5b1": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 摆脱
  "199": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 死斗
  "a76": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 原初的血气
  "a77": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 原初的血潮
  "a78": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 原初的血烟
  "59": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, //复仇
  "49a": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 至黑之夜
  "2ea": { dodge: 0, physics: 0, magic: 1, darkness: 0, condition: "player" }, // 弃明投暗
  "2eb": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 暗影墙
  "766": { dodge: 0, physics: 0, magic: 1, darkness: 0, condition: "player" }, // 暗黑布道
  "32a": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 行尸走肉
  "32b": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 死而不僵
  "cb7": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 出死入生
  "811": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 极光
  "a7a": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 献奉
  "730": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 石之心
  "76a": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 残暴弹
  "728": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 伪装
  "72a": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 星云
  "72f": { dodge: 0, physics: 0, magic: 1, darkness: 0, condition: "player" }, // 光之心
  "72c": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 超火流星
  "a7b": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 刚玉之心
  "a7c": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 刚玉之清
  "4c2": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 神祝祷
  "751": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 节制
  "a94": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 水流幕
  "129": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 鼓舞
  "77e": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 激励
  "77d": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 炽天的幕帘
  "12b": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 野战治疗阵
  "13d": { dodge: 0, physics: 0, magic: 1, darkness: 0, condition: "player" }, // 异想的幻光
  "753": { dodge: 0, physics: 0, magic: 1, darkness: 0, condition: "player" }, // 炽天的幻光
  "a96": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 生命回生法
  "a97": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 怒涛之计
  "351": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 命运之轮
  "761": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 天星交错
  "a9d": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 擢升
  "781": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 中间学派
  "a2f": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 均衡诊断
  "a30": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 齐衡诊断
  "a31": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 均衡预后
  "a3a": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 坚角清汁
  "a3b": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 白牛清汁
  "bbb": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 整体论
  "d25": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 整体盾
  "a34": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 输血
  "a35": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 泛输血
  "4d0": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 心眼
  "49b": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 金刚极意
  "78e": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 行吟
  "79f": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 策动
  "722": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 防守之桑巴
  "a89": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 即兴表演结束
  "1e8": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 残影
  "a8": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 魔罩
  "a8e": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 守护之光
  "a25": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 守护纹
  "a93": { dodge: 0, physics: 0, magic: 1, darkness: 0, condition: "player" }, // 抗死
  "4b9": { dodge: 1, physics: 1, magic: 0, darkness: 0, condition: "player" }, // 亲疏自行
  "4a9": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "enemy" }, // 雪仇
  "4ab": { dodge: 1, physics: 1, magic: 0.5, darkness: 0, condition: "enemy" }, // 牵制
  "4b3": { dodge: 1, physics: 0.5, magic: 1, darkness: 0, condition: "enemy" }, // 昏乱
  "35c": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "enemy" }, // 武装解除
  "848": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 体力增加
  "6b3": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "enemy" }, // 腐臭（臭气）
  "843": { dodge: 0, physics: 0, magic: 1, darkness: 0, condition: "enemy" }, // 智力精神降低（魔法锤）
  "9c4": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 龙之力
  "6ba": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 超硬化
  "9c0": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 玄结界
  "847": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 仙人盾
  "6b7": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 强力守护
  "842": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 哥布防御
  "c2": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 铜墙铁盾
  "c3": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 坚守要塞
  "c4": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 终极堡垒
  "35f": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 原初大地
  "360": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 暗黑之力
  "78b": { dodge: 1, physics: 1, magic: 1, darkness: 1, condition: "player" }, // 灵魂之青
};
export { keigenns };
